apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: mobile-device-controller
build:
  local:
    push: false
    useBuildkit: true
  tagPolicy:
    customTemplate:
      template: "{{.date}}-{{.branch}}-g{{.sha}}"
      components:
        - name: date
          dateTime:
            format: "2006.01.02"
            timezone: "UTC"
        - name: branch
          gitCommit:
            variant: CommitSha
            ignoreChanges: true
        - name: sha
          gitCommit:
            variant: AbbrevCommitSha
  artifacts:
    - image: "com.kvs.mobile-device-controller"
      docker:
        buildArgs:
          IMAGE_TAG: "{{.IMAGE_TAG}}"
      hooks:
        before:
          - command:
              - sh
              - -c
              - echo "CONTAINER_TAG=$SKAFFOLD_IMAGE_TAG">build.env

profiles:
  - name: deviceorbit 
    deploy:
      helm:
        releases:
          - name: mobile-device-controller
            chartPath: chart/mobile-device-controller
            valuesFiles:
              - "chart/mobile-device-controller/values-dev.yaml"
            setValueTemplates:
              image.repository: "{{.IMAGE_REPO}}"
              image.tag: "{{.IMAGE_TAG}}"
