apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: do-create-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: do-pod-creator
subjects:
  - kind: ServiceAccount
    name: mobile-device-controller 
