apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: {{ include "mobile-device-controller.fullname" . }}
  labels:
    {{- include "mobile-device-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
  selector:
    {{- include "mobile-device-controller.selectorLabels" . | nindent 4 }}
